### ISSUE TITLE
Potential raciness w/ parent_channel_ in SendPeerMessage

### ISSUE THREAD

**Issue by darinf** [darinf/ports#15]
Potential raciness w/ parent_channel_ in SendPeerMessage

SendPeerMessage can happen on any thread, and parent_channel_ might not yet be setup, or it might be getting torn down. We probably need some locks, and we may also need to delay sending ports messages until the parent channel is established.

**Comment by krockot** [comment]
Maybe we should go back to holding just the parent name under lock, and use GetPeerChannel on it.

I don't understand how a node can ever be asked to SendPeerMessage before it has a known parent. In SendPeerMessage if there's no parent then either we should be the parent, or we've lost our connection to the parent and everything is bad. Am I missing a case? Where would we ever hear about a peer node without a parent?
