### ISSUE TITLE
Node::MessagesAvailable race with MessagePipeDispatcher shutdown

### ISSUE THREAD

**Issue by darinf** [darinf/ports#2]
A MessagePipeDispatcher could be shutting down (losing its last reference) on one thread, while Node is handling incoming messages for the MessagePipeDispatcher on another thread. Node probably needs a way to extend the lifetime of the PortObserver (implemented by MessagePipeDispatcher).

**Comment by krockot** [comment]
Should be fixed by c602cff301a126c23e6216b63f687ac22bcb8ced
