### ISSUE TITLE
Consider eliminating MessagePipeDispatcher::incoming_messages_

### ISSUE THREAD

**Issue by darinf** [darinf/ports#3]
MessagePipeDispatcher::incoming_messages_ is redundant with ports::Port::message_queue. We should be able to replace incoming_messages_ with a boolean flag indicating whether we expect the port to have messages and then a most recently received message in the case that ReadMessage was given insufficient storage to hold the message. This would also impact the design of PortObserver and how setting peer_closed_ works.

**Comment by krockot** [comment]
Fixed in f9c13ab1ea68de3e6d92f10509013b1932c2131e
