### ISSUE TITLE
Allow NodeController to forward messages

### ISSUE THREAD

**Issue by krockot** [darinf/ports#8]
On Windows, messages which contain platform handles need to be brokered through the parent node. We can trivially detect the presence of 1+ handles in NodeController and send outgoing messages to the parent instead of the peer on Windows.

This requires a new NodeChannel message similar to NodeChannel::PortsMessage but with an additional NodeName field for the destination node.

**Comment by darinf** [comment]
Fixed in commit ccdec2fed9edad1dbfd0bfcd46e9056c784c2b7e
